#!/usr/bin/env bash

URL="https://fuerbringer/post"
ITEMS=""
POSTSDIR="./posts"
OUTDIR="./public"
POSTSOUTDIR="$OUTDIR/post"
POSTLISTOUT="$OUTDIR/posts.html"
AUTHOR="Severin Fürbringer"

HEADHTM=$(cat ./templates/head.tpl.htm)
TAILHTM=$(cat ./templates/tail.tpl.htm)

POSTLIST="" # html

for d in `ls $POSTSDIR | sort -r`; do
  for f in `ls $POSTSDIR/$d/*.md`; do
    POSTTITLE=$(cat $POSTSDIR/$d/$(basename $f | cut -f 1 -d '.').title)
    SLUG=$(basename $POSTSDIR/$d/$f | cut -f 1 -d '.')
    DATE=$(cat $POSTSDIR/$d/$(basename $f | cut -f 1 -d '.').date)
    DATEHUMAN=$(date -d "$DATE" "+%e. %B %Y")
    DATEHUMANPREVIEW=$(date -d "$DATE" "+%d.%m.%y")
    DATERFC=$(date -R -d "$DATE")
    DATEGENERATED=$(date -u +"%d-%m-%Y %H:%M:%S")
    POSTCONTENT=$(pandoc $f)

    cat << EOF > $POSTSOUTDIR/$SLUG.html
    $HEADHTM
    <h1>$POSTTITLE</h1>
    <em>Posted on $DATEHUMAN by $AUTHOR</em>
    $POSTCONTENT
    <p class="post-last-generated"><em>Post was last generated on $DATEGENERATED.</em></p>
    $TAILHTM
EOF

  POSTLIST="$POSTLIST
  <li class=\"post-listing\">
    <a href=\"/post/$SLUG.html\"><em>$POSTTITLE</em> ($DATEHUMANPREVIEW)</a>
  </li>
  "
  
  done
done

POSTLIST="<ul>$POSTLIST</ul>"

cat << EOF > $POSTLISTOUT
$HEADHTM
<h1>Posts</h1>
$POSTLIST
$TAILHTM
EOF
