#!/usr/bin/env bash

TITLE="fuerbringer.info feed"
DESC="fuerbringer.info: Posts about technology."
BASEURL="https://fuerbringer"
URL="$BASEURL/post"
ITEMS="" # xml
POSTSDIR="./posts"
OUTDIR="./public"

for d in `ls $POSTSDIR | sort -r`; do
  for f in `ls $POSTSDIR/$d/*.md`; do
    POSTTITLE=$(cat $POSTSDIR/$d/$(basename $f | cut -f 1 -d '.').title)
    SLUG=$(basename $POSTSDIR/$d/$f | cut -f 1 -d '.')
    DATE=$(cat $POSTSDIR/$d/$(basename $f | cut -f 1 -d '.').date)
    DATERFC=$(date -R -d "$DATE")
    POSTCONTENT=$(pandoc $f)
    ITEMS="$ITEMS
    <item>
      <title>$POSTTITLE</title>
      <guid>$URL/$SLUG.html</guid>
      <pubDate>$DATERFC</pubDate>
      <description><![CDATA[$POSTCONTENT]]></description>
    </item>"
  done
done

cat << EOF > $OUTDIR/rss.xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>$TITLE</title>
    <description>$DESC</description>
    <language>en-us</language>
    <link>$BASEURL/rss.xml</link>
    <atom:link href="$BASEURL/rss.xml" rel="self" type="application/rss+xml" />
    $ITEMS
  </channel>
</rss>
EOF
